### ISSUE TITLE
Issue [CZ]

### ISSUE THREAD

**Issue by ghost** [GamakCZ/RedstoneX#1]
Když zapnu plugin na serveru tak se snazi zaregistrovat bloky pres Block.php i kdyz BlockFactory.php v pmmp asi protože to hodi exception 
`[16:08:31] [Server thread/CRITICAL]: RuntimeException: "Trying to overwrite an already registered block" (EXCEPTION) in "src/pocketmine/block/BlockFactory" at line 348`
tak to skipne na Block.php 
Fix pls :D

**Comment by GamakCZ** [comment]
Stáhni starší verzi

**Comment by ghost** [comment]
A jak si mám givnout ten redstone? Kdyz dam normalni redstone lampu a redstone tak se to nerozsviti jak na tom obrazku

**Comment by ghost** [comment]
Uz jsem na to prisel
Dobry plugin

**Comment by GamakCZ** [comment]
:D
